spring:
  application:
    name: usuario-service

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ChaveSecretaSuperSeguraParaAssinarTokensJwtComPeloMenos256BitsDeTamanho
  expiration: 3600000 # 1 hora em milissegundos

server:
  port: 8083